### ISSUE TITLE
Issue with date on graph

### ISSUE THREAD

**Issue by chatainsim** [dynasticorpheus/ws50-sync#1]
Hello,
I've tested your script and date are correct except that the graph is wrong.
All data are display in the last 24 hours:
![capture](https://cloud.githubusercontent.com/assets/1167931/13106185/3f9a1a6a-d567-11e5-9607-ba3d72329702.PNG)

Only one date is display on the other graph:
![capture1](https://cloud.githubusercontent.com/assets/1167931/13106199/5292ec3c-d567-11e5-9995-24aeed060155.PNG)
![capture2](https://cloud.githubusercontent.com/assets/1167931/13106206/5561a958-d567-11e5-8077-2055a48dc0ab.PNG)

Can you help me with this ?

Thanks

**Comment by dynasticorpheus** [comment]
@chatainsim Did you run the script while domoticz was running? If not can you clear/recreate the two sensors and try again whilst domoticz is running.

**Comment by chatainsim** [comment]
Yes, I did this with Domoticz turn off.
I've recreated both sensors and ran again the script but he add nothing to db:

```
[-] Database /opt/domoticz/domoticz.db
[-] Authenticating at account.withings.com
[-] Downloading data newer than 2016-02-18 23:15:00
[-] Updating database with 0 CO2 measurements [TRUE]
[-] Updating database with 0 TEMPERATURE measurements [TRUE]
[-] Committing and closing database
```

**Comment by dynasticorpheus** [comment]
@chatainsim From your output is seems the script does find a date entry in the DB and therefore only tries to fetch data newer than 2016-02-18 23:15:00. 

Please download the latest version of the script and first run it with option **--remove** so we are sure both meters are cleared completely before trying again. As said _keep domoticz running_ otherwise the DB journal will revert any changes we did whilst domoticz was offline.

**Comment by chatainsim** [comment]
I tried the remove then restart the script, It's working but I only have one day of data.
![capture](https://cloud.githubusercontent.com/assets/1167931/13172837/8befe82e-d6fa-11e5-8fb0-a2593079285a.PNG)

![capture](https://cloud.githubusercontent.com/assets/1167931/13172862/adf290f2-d6fa-11e5-90ef-65665ebb201a.PNG)

**Comment by chatainsim** [comment]
I tried to ran the script again and this time it's like the first time all data is store in the 24 hours graph.

Edit: Nevermind, If I wait a little longer, all the data is remove and only one day is kept.

**Comment by dynasticorpheus** [comment]
@chatainsim So it is now working as expected?

**Comment by chatainsim** [comment]
I don't know, does the script should get all data ? Because I have data since begining of 2015 and there is nothing in the graph.

**Comment by dynasticorpheus** [comment]
@chatainsim I think I need to work a bit more on the script because although we are loading the complete data set the system does not build the month / year graph retrospectively. So for now I would just run the script as-is once or twice a day and you will see all graphs being created but not with historical data just yet. Now investigating how this works so we can enhance the script to also do this.

**Comment by chatainsim** [comment]
Ok, thankyou @dynasticorpheus !

**Comment by dynasticorpheus** [comment]
@chatainsim I have updated the script and it should now handle the complete history.

Run the script **once** with the additional options: **--full --delete**

Once completed you should just simply run the script without those two extra options once or twice a day.

**Comment by chatainsim** [comment]
Thank you @dynasticorpheus, it working fine with --full --remove !
Now I have all data in graphs !
